name = "threads-auto-scheduler"
main = "src/index.js"
compatibility_date = "2024-03-15"

[triggers]
crons = ["*/5 * * * *"] # Every 5 minutes (to stay within free tier KV limits)

[[kv_namespaces]]
binding = "SCHEDULES_KV"
id = "993f06da43da4729b83fa750e3456df7"

[vars]
API_SECRET = "threads-auto-secret-2026"
